"""
inference_power_eta_split.py

Conditional Diffusion Framework power analysis testing Y3 conditionally
independent of Y2 given Y1, using deterministic train/inference split datasets.

Split setup:
- n_train in [200, 500, 1000]
- n_infer map: 200->200, 500->300, 1000->400
- Diffusion models are trained on the train split only.
- tau and Monte Carlo tau(d) values are computed on the inference split only.
"""

import argparse
import os
import pickle
import random

import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import QuantileTransformer, StandardScaler

from _project_setup import PROJECT_ROOT
from utils.conditional_ddpm import generate_conditional_samples, train_all_conditional_ddpms
from utils.mcodec import mcodec


TRAIN_TO_INFER = {
    200: 200,
    500: 300,
    1000: 400,
}


def seed_everything(seed: int) -> None:
    """Set all random seeds for reproducibility."""
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def format_param(value: float) -> str:
    return f"{value:.10g}"


def load_split_dataset(csv_path: str, n_train: int, n_infer: int):
    """Load split CSV and return train/infer arrays of shape [n, 30]."""
    if not os.path.exists(csv_path):
        raise FileNotFoundError(
            f"Missing split dataset: {csv_path}. "
            "Generate it first with DataGen_inference_split.py."
        )

    df = pd.read_csv(csv_path)
    feature_cols = [f"X{i}" for i in range(30)]
    required_cols = ["split"] + feature_cols
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Dataset {csv_path} is missing required columns: {missing}")

    train_df = df[df["split"] == "train"]
    infer_df = df[df["split"] == "infer"]

    if len(train_df) != n_train or len(infer_df) != n_infer:
        raise ValueError(
            f"Split size mismatch in {csv_path}: "
            f"expected train={n_train}, infer={n_infer}, "
            f"got train={len(train_df)}, infer={len(infer_df)}"
        )

    train_data = train_df[feature_cols].to_numpy(dtype=np.float32)
    infer_data = infer_df[feature_cols].to_numpy(dtype=np.float32)
    return train_data, infer_data


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Conditional Diffusion Framework power analysis with split datasets "
            "(power_eta)."
        )
    )
    parser.add_argument("--device", type=str, default="cuda:0")
    parser.add_argument("--n_seeds", type=int, default=100, help="Number of seeds (datasets) to test")
    parser.add_argument("--monte_carlo_size", type=int, default=100, help="Number of Y3 samples per inference set (D)")
    parser.add_argument("--monte_carlo_batch_size", type=int, default=50, help="Batch size for sampling Y3")
    parser.add_argument("--use_standard_scaler", action="store_true", help="Use StandardScaler instead of QuantileTransformer")
    parser.add_argument("--eta", type=float, default=None, help="Specific eta value to test (overrides default grid)")
    parser.add_argument(
        "--data_dir",
        type=str,
        default="./data/inference_power_eta_split",
        help="Directory containing split datasets generated by DataGen_inference_split.py",
    )
    args = parser.parse_args()

    device = args.device
    n_seeds = args.n_seeds
    D = args.monte_carlo_size
    D_batch = args.monte_carlo_batch_size if args.monte_carlo_batch_size is not None else D

    training_samples_list = [200, 500, 1000]
    if args.eta is not None:
        eta_values_list = [args.eta]
    else:
        eta_values_list = [0.5, 0.7, 1.0, 2.0, 3.0]

    print(f"Testing training sample sizes: {training_samples_list}")
    print(f"Testing eta values: {eta_values_list}")
    print(f"Inference sample mapping: {TRAIN_TO_INFER}")

    d_in = 30

    hidden_dims_conditional = [640, 320, 320, 320, 160]
    dim_t_conditional = 64

    n_steps = 1000
    n_epochs = 3000
    lr = 5e-5

    os.makedirs("./ckpt/inference_power_eta_split", exist_ok=True)
    os.makedirs("./results", exist_ok=True)
    os.makedirs("./results/inference_power_eta_split", exist_ok=True)

    groups = torch.zeros(d_in, dtype=torch.long)
    groups[0:10] = 0
    groups[10:20] = 1
    groups[20:30] = 2

    # Fork model (misspecified when eta != 0)
    A = np.array(
        [
            [0, 1, 1],
            [0, 0, 0],
            [0, 0, 0],
        ],
        dtype=np.float32,
    )

    print("\nConditional Diffusion Framework configuration for split power test (eta):")
    print("  Model structure: fork (G0->G1, G0->G2), misspecified under H1")

    results = []
    scaler_suffix = "_std" if args.use_standard_scaler else "_qt"

    for eta in eta_values_list:
        eta_str = format_param(eta)
        print(f"\n{'=' * 80}")
        print(f"ETA VALUE: {eta} (testing power under H1: Y3 not indep Y2 | Y1)")
        print(f"{'=' * 80}")

        results_file = (
            f"./results/inference_power_eta_split/inference_power_eta{eta_str}_results{scaler_suffix}.csv"
        )
        if os.path.exists(results_file):
            os.remove(results_file)

        eta_results = []

        for n_samples_train in training_samples_list:
            n_samples_infer = TRAIN_TO_INFER[n_samples_train]
            print(f"\n{'=' * 70}")
            print(
                f"TRAINING SAMPLE SIZE: {n_samples_train} | "
                f"INFERENCE SAMPLE SIZE: {n_samples_infer} (eta={eta})"
            )
            print(f"{'=' * 70}")

            for seed in range(n_seeds):
                print(f"\n{'=' * 50}")
                print(
                    f"SEED {seed} (eta={eta}, "
                    f"n_train={n_samples_train}, n_infer={n_samples_infer})"
                )
                print(f"{'=' * 50}")

                seed_everything(seed)

                data_file = os.path.join(
                    args.data_dir,
                    f"power_eta_eta{eta_str}_n{n_samples_train}_m{n_samples_infer}_seed_{seed}.csv",
                )
                train_data, infer_data = load_split_dataset(data_file, n_samples_train, n_samples_infer)
                print(f"Loaded split data: {data_file}")
                print(f"  train shape: {train_data.shape}, infer shape: {infer_data.shape}")

                if args.use_standard_scaler:
                    print("Using StandardScaler (fit on train split only)")
                    scaler = StandardScaler()
                    train_data_norm = scaler.fit_transform(train_data)
                    infer_data_norm = scaler.transform(infer_data)
                else:
                    n_quantiles = min(1000, n_samples_train)
                    print(
                        f"Using QuantileTransformer (fit on train split only) "
                        f"with {n_quantiles} quantiles"
                    )
                    qt = QuantileTransformer(
                        output_distribution="normal",
                        random_state=seed,
                        n_quantiles=n_quantiles,
                        subsample=min(100000, n_samples_train),
                    )
                    train_data_norm = qt.fit_transform(train_data)
                    infer_data_norm = qt.transform(infer_data)

                train_data_norm_t = torch.tensor(train_data_norm, dtype=torch.float32)

                print("\n--- Training Conditional Diffusion Models (train split only) ---")
                print(f"    hidden_dims={hidden_dims_conditional}, dim_t={dim_t_conditional}")
                print("    Model remains misspecified intentionally for power test")
                models = train_all_conditional_ddpms(
                    train_data=train_data_norm_t,
                    groups=groups,
                    A=A,
                    hidden_dims=hidden_dims_conditional,
                    dim_t=dim_t_conditional,
                    n_steps=n_steps,
                    n_epochs=n_epochs,
                    lr=lr,
                    device=device,
                    verbose=True,
                )

                checkpoint_dir = (
                    f"./ckpt/inference_power_eta_split/conditional_eta{eta_str}_"
                    f"n{n_samples_train}_m{n_samples_infer}_seed_{seed}"
                )
                os.makedirs(checkpoint_dir, exist_ok=True)
                models_path = os.path.join(checkpoint_dir, "models.pkl")
                with open(models_path, "wb") as f:
                    pickle.dump(models, f)
                print(f"Models saved to: {models_path}")

                print("\n--- Computing MCODEC test on inference split ---")
                Y1_infer = infer_data[:, 0:10]
                Y2_infer = infer_data[:, 10:20]
                Y3_infer = infer_data[:, 20:30]

                print("  Computing tau = MCODEC(Y3_infer, Y2_infer, Y1_infer)...")
                tau_observed = mcodec(Y3_infer, Y2_infer, Y1_infer)
                print(f"  tau (observed) = {tau_observed:.6f}")

                print(f"  Sampling Y3 {D} times from trained models conditioned on inference Y1/Y2...")
                tau_samples = []

                mc_batch_sizes = [D_batch] * (D // D_batch) + ([D % D_batch] if D % D_batch != 0 else [])

                for batch_idx, mc_batch_size in enumerate(mc_batch_sizes):
                    print(
                        f"    Batch {batch_idx + 1}/{len(mc_batch_sizes)}: "
                        f"Generating {mc_batch_size} Y3 samples..."
                    )

                    do_vars = {i: infer_data_norm[:, i] for i in range(20)}
                    sample_vars = list(range(20, 30))

                    Y3_sampled_batch_norm = generate_conditional_samples(
                        models=models,
                        groups=groups,
                        A=A,
                        do_vars=do_vars,
                        sample_vars=sample_vars,
                        n_samples=mc_batch_size,
                        device=device,
                    )

                    Y3_sampled_batch_norm = Y3_sampled_batch_norm.cpu().numpy()

                    for i in range(mc_batch_size):
                        full_data_norm = np.zeros((n_samples_infer, 30), dtype=np.float32)
                        full_data_norm[:, 0:20] = infer_data_norm[:, 0:20]
                        full_data_norm[:, 20:30] = Y3_sampled_batch_norm[i]

                        if args.use_standard_scaler:
                            full_data = scaler.inverse_transform(full_data_norm)
                        else:
                            full_data = qt.inverse_transform(full_data_norm)

                        Y3_sampled = full_data[:, 20:30]
                        tau_d = mcodec(Y3_sampled, Y2_infer, Y1_infer)
                        tau_samples.append(tau_d)

                print(f"  Generated {len(tau_samples)} tau(d) values")
                print(f"  tau(d) range: [{min(tau_samples):.6f}, {max(tau_samples):.6f}]")
                print(f"  tau(d) mean: {np.mean(tau_samples):.6f}")

                num_larger_or_equal = sum(1 for tau_d in tau_samples if tau_d >= tau_observed)
                p_value = (1 + num_larger_or_equal) / (D + 1)

                print("\n  Results:")
                print(f"    tau (observed):              {tau_observed:.6f}")
                print(f"    # of tau(d) >= tau:          {num_larger_or_equal}")
                print(f"    p-value:                     {p_value:.6f}")

                result = {
                    "eta": eta,
                    "n_samples_train": n_samples_train,
                    "n_samples_infer": n_samples_infer,
                    "seed": seed,
                    "framework": "conditional",
                    "tau_observed": tau_observed,
                    "p_value": p_value,
                    "num_larger_or_equal": num_larger_or_equal,
                    "D": D,
                    "use_standard_scaler": args.use_standard_scaler,
                }

                for d, tau_d in enumerate(tau_samples):
                    result[f"tau_d_{d + 1}"] = tau_d

                eta_results.append(result)

                print(f"\n  Saving results after seed {seed}...")
                eta_results_df = pd.DataFrame(eta_results)
                eta_results_df.to_csv(results_file, index=False)

                current_data = eta_results_df[eta_results_df["n_samples_train"] == n_samples_train]
                if len(current_data) > 0:
                    mean_p_value = current_data["p_value"].mean()
                    mean_tau = current_data["tau_observed"].mean()
                    rejection_rate = (current_data["p_value"] <= 0.05).mean()
                    print(
                        f"    Current summary for eta={eta}, n_train={n_samples_train}, "
                        f"n_infer={n_samples_infer} (up to seed {seed}):"
                    )
                    print(f"      Mean p-value:   {mean_p_value:.6f}")
                    print(f"      Mean tau:       {mean_tau:.6f}")
                    print(f"      Rejection rate: {rejection_rate:.4f}")

        eta_results_df = pd.DataFrame(eta_results)
        eta_results_df.to_csv(results_file, index=False)

        print(f"\n{'=' * 70}")
        print(f"Creating summary statistics for eta={eta}...")

        summary_cols = ["tau_observed", "p_value"]
        summary = (
            eta_results_df.groupby(["n_samples_train", "n_samples_infer"])[summary_cols]
            .agg(["mean", "std", "min", "max", "count"])
            .round(6)
        )
        summary.to_csv(f"./results/inference_power_eta_split/summary_eta{eta_str}{scaler_suffix}.csv")

        print("\nResults saved to ./results/inference_power_eta_split/:")
        print(f"- Detailed results: inference_power_eta{eta_str}_results{scaler_suffix}.csv")
        print(f"- Summary: summary_eta{eta_str}{scaler_suffix}.csv")
        print(f"Total results for eta={eta}: {len(eta_results_df)} rows")

        eta_results_df["reject_005"] = eta_results_df["p_value"] <= 0.05
        power_by_n = eta_results_df.groupby(["n_samples_train", "n_samples_infer"])["reject_005"].mean()
        print("Power at alpha=0.05 (rejection rate under H1):")
        print(power_by_n)

        results.extend(eta_results)

    if len(eta_values_list) > 1:
        print(f"\n{'=' * 70}")
        print("Creating combined results across all eta values...")
        combined_results_df = pd.DataFrame(results)
        combined_file = (
            f"./results/inference_power_eta_split/inference_power_eta_combined_results{scaler_suffix}.csv"
        )
        combined_results_df.to_csv(combined_file, index=False)

        combined_summary = (
            combined_results_df.groupby(["eta", "n_samples_train", "n_samples_infer"])["p_value"]
            .agg(["count", "mean", "std"])
            .round(6)
        )
        combined_summary.to_csv(f"./results/inference_power_eta_split/combined_summary{scaler_suffix}.csv")

        combined_results_df["reject_005"] = combined_results_df["p_value"] <= 0.05
        power_table = combined_results_df.groupby(["eta", "n_samples_train", "n_samples_infer"])["reject_005"].mean()
        print("\nPower curves (rejection rate at alpha=0.05):")
        print(power_table)
        print(f"\nCombined results saved to: {combined_file}")


if __name__ == "__main__":
    main()
