"""
long_chain_distribution_comparison.py

Distributional comparison for the long-chain structure under
do(Y2 = y2_values, Y5 = y5_values).

Conditional framework:
  Samples the causal post-intervention distribution of (Y1, Y3, Y4, Y6).

Standard framework:
  Samples the observational conditional distribution
  (Y1, Y3, Y4, Y6) | Y2 = y2_values, Y5 = y5_values.

Both are compared against a fixed true do-reference sample generated by
long_chain_data_comparison.py using energy distance and RBF MMD.

Training data is loaded from files generated by long_chain_data_comparison.py
so competitors can use exactly the same dataset for each seed and training
size.
"""

import argparse
import os
import random

import numpy as np
import pandas as pd
import torch
import torch.optim as optim
from sklearn.preprocessing import QuantileTransformer, StandardScaler

from _project_setup import PROJECT_ROOT
from long_chain_data_comparison import TARGET_INDICES, training_data_path
from utils.conditional_ddpm import generate_conditional_samples, train_all_conditional_ddpms
from utils.ddpm import MyDDPM, generate_imputation, training_loop
from utils.utils_model import MLPDiffusionContinuous


N_FEATURES = 30
Y2_INDICES = np.arange(5, 10)
Y5_INDICES = np.arange(20, 25)


def seed_everything(seed):
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def long_chain_groups_and_adjacency():
    groups = torch.zeros(N_FEATURES, dtype=torch.long)
    groups[0:5] = 0
    groups[5:10] = 1
    groups[10:15] = 2
    groups[15:20] = 3
    groups[20:25] = 4
    groups[25:30] = 5

    adjacency = torch.tensor(
        [
            [0, 1, 0, 0, 0, 0],
            [0, 0, 1, 0, 0, 0],
            [0, 0, 0, 1, 0, 0],
            [0, 0, 0, 0, 1, 0],
            [0, 0, 0, 0, 0, 1],
            [0, 0, 0, 0, 0, 0],
        ],
        dtype=torch.float32,
    )
    return groups, adjacency


def load_reference(reference_path, n_samples_eval=None):
    if not os.path.exists(reference_path):
        raise FileNotFoundError(
            f"Missing reference file: {reference_path}\n"
            "Create it first with long_chain_data_comparison.py."
        )

    data = np.load(reference_path, allow_pickle=True)
    required = {"target_samples", "target_indices", "y2_values", "y5_values"}
    missing = required.difference(data.files)
    if missing:
        raise ValueError(f"Reference file is missing fields: {sorted(missing)}")

    target_samples = np.asarray(data["target_samples"], dtype=float)
    target_indices = np.asarray(data["target_indices"], dtype=int)
    y2_values = np.asarray(data["y2_values"], dtype=float)
    y5_values = np.asarray(data["y5_values"], dtype=float)

    if not np.array_equal(target_indices, TARGET_INDICES):
        raise ValueError(
            "Reference target indices do not match expected (Y1, Y3, Y4, Y6) indices."
        )
    if y2_values.shape != (5,) or y5_values.shape != (5,):
        raise ValueError("Reference y2_values and y5_values must both be 5-vectors.")

    if n_samples_eval is not None:
        if n_samples_eval > target_samples.shape[0]:
            raise ValueError(
                f"Requested n_samples_eval={n_samples_eval}, but reference only has "
                f"{target_samples.shape[0]} rows."
            )
        target_samples = target_samples[:n_samples_eval]

    metadata = {
        "reference_seed": int(np.asarray(data["seed"]).item()) if "seed" in data.files else None,
        "sigma": float(np.asarray(data["sigma"]).item()) if "sigma" in data.files else None,
        "correlation": float(np.asarray(data["correlation"]).item())
        if "correlation" in data.files
        else None,
    }

    return target_samples, y2_values, y5_values, metadata


def fit_scaler(train_data, use_standard_scaler, seed):
    if use_standard_scaler:
        scaler = StandardScaler()
    else:
        scaler = QuantileTransformer(
            output_distribution="normal",
            random_state=seed,
            n_quantiles=min(1000, train_data.shape[0]),
            subsample=min(100000, train_data.shape[0]),
        )
    train_data_norm = scaler.fit_transform(train_data)
    return scaler, train_data_norm


def load_training_data(training_data_dir, n_samples_train, seed, sigma=None, correlation=None):
    path = training_data_path(training_data_dir, n_samples_train, seed)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing training data file: {path}\n"
            "Generate training data first with:\n"
            "  python long_chain_data_comparison.py\n"
            "or pass --training_data_dir to the directory containing train_n*_seed*.npz files."
        )

    data = np.load(path, allow_pickle=True)
    if "train_data" not in data.files:
        raise ValueError(f"Training data file does not contain 'train_data': {path}")

    train_data = np.asarray(data["train_data"], dtype=float)
    if train_data.shape != (n_samples_train, N_FEATURES):
        raise ValueError(
            f"Unexpected train_data shape in {path}: {train_data.shape}; "
            f"expected ({n_samples_train}, {N_FEATURES})."
        )

    file_seed = int(np.asarray(data["seed"]).item()) if "seed" in data.files else None
    file_n = (
        int(np.asarray(data["n_samples_train"]).item())
        if "n_samples_train" in data.files
        else None
    )
    if file_seed is not None and file_seed != seed:
        raise ValueError(f"Seed mismatch in {path}: file has {file_seed}, expected {seed}.")
    if file_n is not None and file_n != n_samples_train:
        raise ValueError(
            f"Training-size mismatch in {path}: file has {file_n}, expected {n_samples_train}."
        )

    if sigma is not None and "sigma" in data.files:
        file_sigma = float(np.asarray(data["sigma"]).item())
        if not np.isclose(file_sigma, sigma):
            print(f"Warning: {path} has sigma={file_sigma}, requested sigma={sigma}.")
    if correlation is not None and "correlation" in data.files:
        file_correlation = float(np.asarray(data["correlation"]).item())
        if not np.isclose(file_correlation, correlation):
            print(
                f"Warning: {path} has correlation={file_correlation}, "
                f"requested correlation={correlation}."
            )

    return train_data, path


def intervention_row(y2_values, y5_values):
    row = np.zeros((1, N_FEATURES))
    row[:, Y2_INDICES] = y2_values
    row[:, Y5_INDICES] = y5_values
    return row


def normalized_intervention_row(scaler, y2_values, y5_values):
    return scaler.transform(intervention_row(y2_values, y5_values))[0]


def inverse_conditional_target_samples(scaler, target_norm, intervention_norm):
    full_norm = np.zeros((target_norm.shape[0], N_FEATURES))
    full_norm[:, TARGET_INDICES] = target_norm
    full_norm[:, Y2_INDICES] = intervention_norm[Y2_INDICES]
    full_norm[:, Y5_INDICES] = intervention_norm[Y5_INDICES]
    full_orig = scaler.inverse_transform(full_norm)
    return full_orig[:, TARGET_INDICES]


def generate_conditional_do_samples(
    models,
    groups,
    adjacency,
    scaler,
    y2_values,
    y5_values,
    n_samples,
    batch_size,
    device,
):
    intervention_norm = normalized_intervention_row(scaler, y2_values, y5_values)
    do_vars = {}
    for idx in list(Y2_INDICES) + list(Y5_INDICES):
        do_vars[int(idx)] = torch.tensor(
            [intervention_norm[idx]], dtype=torch.float32, device=device
        )

    batches = []
    for start in range(0, n_samples, batch_size):
        current_batch = min(batch_size, n_samples - start)
        print(f"    Conditional sampling batch {start // batch_size + 1}: {current_batch}")
        samples_norm = generate_conditional_samples(
            models=models,
            groups=groups,
            A=adjacency.cpu().numpy() if isinstance(adjacency, torch.Tensor) else adjacency,
            do_vars=do_vars,
            sample_vars=TARGET_INDICES.tolist(),
            n_samples=current_batch,
            device=device,
            verbose=False,
        )
        target_norm = samples_norm[:, 0, :].detach().cpu().numpy()
        batches.append(inverse_conditional_target_samples(scaler, target_norm, intervention_norm))

    return np.concatenate(batches, axis=0)


def generate_standard_conditional_samples(
    ddpm,
    scaler,
    y2_values,
    y5_values,
    n_samples,
    batch_size,
    resampling_steps,
):
    batches = []
    base_row = intervention_row(y2_values, y5_values)

    for start in range(0, n_samples, batch_size):
        current_batch = min(batch_size, n_samples - start)
        print(f"    Standard sampling batch {start // batch_size + 1}: {current_batch}")

        batch_orig = np.repeat(base_row, repeats=current_batch, axis=0)
        batch_norm = scaler.transform(batch_orig)
        input_norm = torch.tensor(batch_norm, dtype=torch.float32)

        input_mask = torch.zeros(input_norm.shape, dtype=torch.float32)
        input_mask[:, Y2_INDICES] = 1.0
        input_mask[:, Y5_INDICES] = 1.0

        output_norm = generate_imputation(
            ddpm,
            input_norm,
            input_mask,
            resampling_steps=resampling_steps,
        )
        output_orig = scaler.inverse_transform(output_norm.detach().cpu().numpy())
        batches.append(output_orig[:, TARGET_INDICES])

    return np.concatenate(batches, axis=0)


def mean_pairwise_euclidean(x, y, chunk_size):
    x = np.asarray(x, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)
    y_t = y.T
    y_norm = np.sum(y * y, axis=1)

    total = 0.0
    for start in range(0, x.shape[0], chunk_size):
        x_chunk = x[start : start + chunk_size]
        x_norm = np.sum(x_chunk * x_chunk, axis=1)
        sq = x_norm[:, None] + y_norm[None, :] - 2.0 * x_chunk.dot(y_t)
        np.maximum(sq, 0.0, out=sq)
        np.sqrt(sq, out=sq)
        total += float(np.sum(sq))

    return total / (x.shape[0] * y.shape[0])


def energy_distance(reference, generated, chunk_size):
    cross = mean_pairwise_euclidean(reference, generated, chunk_size)
    ref_ref = mean_pairwise_euclidean(reference, reference, chunk_size)
    gen_gen = mean_pairwise_euclidean(generated, generated, chunk_size)
    return max(2.0 * cross - ref_ref - gen_gen, 0.0)


def median_heuristic_sigma2(reference, generated, max_points, seed):
    pooled = np.vstack([reference, generated]).astype(np.float64, copy=False)
    if pooled.shape[0] > max_points:
        rng = np.random.default_rng(seed)
        idx = rng.choice(pooled.shape[0], size=max_points, replace=False)
        pooled = pooled[idx]

    norms = np.sum(pooled * pooled, axis=1)
    sq = norms[:, None] + norms[None, :] - 2.0 * pooled.dot(pooled.T)
    np.maximum(sq, 0.0, out=sq)

    upper = sq[np.triu_indices(sq.shape[0], k=1)]
    upper = upper[upper > 0]
    if upper.size == 0:
        return 1.0
    return max(float(np.median(upper)), 1e-12)


def mean_rbf_kernel(x, y, sigma2, chunk_size):
    x = np.asarray(x, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)
    y_t = y.T
    y_norm = np.sum(y * y, axis=1)
    gamma = 1.0 / (2.0 * sigma2)

    total = 0.0
    for start in range(0, x.shape[0], chunk_size):
        x_chunk = x[start : start + chunk_size]
        x_norm = np.sum(x_chunk * x_chunk, axis=1)
        sq = x_norm[:, None] + y_norm[None, :] - 2.0 * x_chunk.dot(y_t)
        np.maximum(sq, 0.0, out=sq)
        kernel = np.exp(-gamma * sq)
        total += float(np.sum(kernel))

    return total / (x.shape[0] * y.shape[0])


def mmd2_rbf(reference, generated, chunk_size, median_subset_size, seed):
    sigma2 = median_heuristic_sigma2(reference, generated, median_subset_size, seed)
    k_xx = mean_rbf_kernel(reference, reference, sigma2, chunk_size)
    k_yy = mean_rbf_kernel(generated, generated, sigma2, chunk_size)
    k_xy = mean_rbf_kernel(reference, generated, sigma2, chunk_size)
    return max(k_xx + k_yy - 2.0 * k_xy, 0.0), sigma2


def compute_metrics(reference, generated, chunk_size, median_subset_size, seed):
    if reference.shape != generated.shape:
        raise ValueError(
            f"Shape mismatch: reference {reference.shape}, generated {generated.shape}"
        )

    energy = energy_distance(reference, generated, chunk_size)
    mmd2, sigma2 = mmd2_rbf(reference, generated, chunk_size, median_subset_size, seed)
    return {
        "energy_distance": energy,
        "mmd2": mmd2,
        "mmd_sigma2": sigma2,
    }


def add_intervention_columns(row, y2_values, y5_values):
    for i, value in enumerate(y2_values):
        row[f"y2_{i}"] = float(value)
    for i, value in enumerate(y5_values):
        row[f"y5_{i}"] = float(value)
    return row


def main():
    parser = argparse.ArgumentParser(
        description="Long-chain distribution comparison under do(Y2, Y5)."
    )
    parser.add_argument("--device", type=str, default="cuda:0")
    parser.add_argument("--n_seeds", type=int, default=50)
    parser.add_argument(
        "--training_samples",
        type=int,
        nargs="+",
        default=[500, 1000, 2000, 5000],
    )
    parser.add_argument(
        "--reference_path",
        type=str,
        default="./data/long_chain_distribution_comparison/true_do_reference.npz",
    )
    parser.add_argument(
        "--training_data_dir",
        type=str,
        default="./data/long_chain_distribution_comparison/training",
    )
    parser.add_argument("--n_samples_eval", type=int, default=None)
    parser.add_argument("--sample_batch_size", type=int, default=5000)
    parser.add_argument("--standard_resampling_steps", type=int, default=20)
    parser.add_argument("--metric_chunk_size", type=int, default=256)
    parser.add_argument("--median_subset_size", type=int, default=1000)
    parser.add_argument("--use_standard_scaler", action="store_true")
    parser.add_argument("--n_steps", type=int, default=1000)
    parser.add_argument("--n_epochs", type=int, default=3000)
    parser.add_argument("--lr", type=float, default=5e-5)
    parser.add_argument("--sigma", type=float, default=1.0)
    parser.add_argument("--correlation", type=float, default=0.5)
    parser.add_argument(
        "--results_dir",
        type=str,
        default="./results/long_chain_distribution_comparison",
    )
    parser.add_argument("--verbose_training", action="store_true")
    args = parser.parse_args()

    device = args.device
    if device.startswith("cuda") and not torch.cuda.is_available():
        print(f"CUDA is not available. Using CPU instead of {device}.")
        device = "cpu"

    os.makedirs(args.results_dir, exist_ok=True)

    reference, y2_values, y5_values, ref_meta = load_reference(
        args.reference_path, n_samples_eval=args.n_samples_eval
    )
    n_eval = reference.shape[0]

    groups_conditional, adjacency_conditional = long_chain_groups_and_adjacency()
    groups_standard = torch.zeros(N_FEATURES, dtype=torch.long)
    adjacency_standard = torch.ones((1, 1), dtype=torch.float32)

    d_time_standard = 128
    hidden_dims_standard = [1024, 512, 512, 512, 256]
    hidden_dims_conditional = [512, 256, 256, 256, 128]
    dim_t_conditional = 128

    scaler_suffix = "_std" if args.use_standard_scaler else "_qt"
    results_file = os.path.join(
        args.results_dir, f"long_chain_distribution_comparison_results{scaler_suffix}.csv"
    )
    summary_file = os.path.join(
        args.results_dir, f"long_chain_distribution_comparison_summary{scaler_suffix}.csv"
    )

    print("\nLong-chain distribution comparison")
    print(f"Reference path: {args.reference_path}")
    print(f"Reference target shape: {reference.shape}")
    print(f"Y2 intervention: {y2_values}")
    print(f"Y5 intervention: {y5_values}")
    print(f"Training data dir: {args.training_data_dir}")
    print(f"Training sizes: {args.training_samples}")
    print(f"Seeds: 0 to {args.n_seeds - 1}")
    print(f"Sample batch size: {args.sample_batch_size}")
    print(f"Metric chunk size: {args.metric_chunk_size}")

    if os.path.exists(results_file):
        os.remove(results_file)

    results = []

    for seed in range(args.n_seeds):
        print(f"\n{'=' * 80}")
        print(f"SEED {seed}")
        print(f"{'=' * 80}")
        seed_everything(seed)

        for n_samples_train in args.training_samples:
            print(f"\n{'-' * 80}")
            print(f"Seed {seed} | training samples: {n_samples_train}")
            print(f"{'-' * 80}")

            train_data, train_data_path_used = load_training_data(
                training_data_dir=args.training_data_dir,
                n_samples_train=n_samples_train,
                seed=seed,
                sigma=args.sigma,
                correlation=args.correlation,
            )
            print(f"Loaded training data: {train_data_path_used}")
            scaler, train_data_norm = fit_scaler(train_data, args.use_standard_scaler, seed)
            train_tensor = torch.tensor(train_data_norm, dtype=torch.float32)

            print("\nTraining conditional framework")
            seed_everything(seed)
            conditional_models = train_all_conditional_ddpms(
                train_data=train_tensor,
                groups=groups_conditional,
                A=adjacency_conditional.cpu().numpy(),
                hidden_dims=hidden_dims_conditional,
                dim_t=dim_t_conditional,
                n_steps=args.n_steps,
                n_epochs=args.n_epochs,
                lr=args.lr,
                device=device,
                verbose=args.verbose_training,
            )

            print("\nSampling conditional do-distribution")
            conditional_samples = generate_conditional_do_samples(
                models=conditional_models,
                groups=groups_conditional,
                adjacency=adjacency_conditional,
                scaler=scaler,
                y2_values=y2_values,
                y5_values=y5_values,
                n_samples=n_eval,
                batch_size=args.sample_batch_size,
                device=device,
            )

            conditional_metrics = compute_metrics(
                reference,
                conditional_samples,
                chunk_size=args.metric_chunk_size,
                median_subset_size=args.median_subset_size,
                seed=100000 + seed,
            )
            conditional_row = {
                "seed": seed,
                "n_samples_train": n_samples_train,
                "framework": "conditional",
                "n_eval": n_eval,
                "use_standard_scaler": args.use_standard_scaler,
                "reference_seed": ref_meta["reference_seed"],
                "standard_resampling_steps": np.nan,
                **conditional_metrics,
            }
            results.append(add_intervention_columns(conditional_row, y2_values, y5_values))
            print(
                "Conditional metrics: "
                f"energy={conditional_metrics['energy_distance']:.6f}, "
                f"mmd2={conditional_metrics['mmd2']:.6f}, "
                f"sigma2={conditional_metrics['mmd_sigma2']:.6f}"
            )

            del conditional_models
            if device.startswith("cuda"):
                torch.cuda.empty_cache()

            print("\nTraining standard framework")
            seed_everything(seed)
            model_standard = MLPDiffusionContinuous(
                d_in=N_FEATURES,
                hidden_dims=hidden_dims_standard,
                dim_t=d_time_standard,
                groups_0=groups_standard,
                A=adjacency_standard,
            )
            ddpm_standard = MyDDPM(model_standard, n_steps=args.n_steps, device=device)
            optimizer_standard = optim.Adam(ddpm_standard.network.parameters(), lr=args.lr)
            training_loop(
                train_tensor,
                ddpm_standard,
                args.n_epochs,
                optimizer_standard,
                device=device,
                store_path=None,
            )

            print("\nSampling standard conditional distribution")
            standard_samples = generate_standard_conditional_samples(
                ddpm=ddpm_standard,
                scaler=scaler,
                y2_values=y2_values,
                y5_values=y5_values,
                n_samples=n_eval,
                batch_size=args.sample_batch_size,
                resampling_steps=args.standard_resampling_steps,
            )

            standard_metrics = compute_metrics(
                reference,
                standard_samples,
                chunk_size=args.metric_chunk_size,
                median_subset_size=args.median_subset_size,
                seed=200000 + seed,
            )
            standard_row = {
                "seed": seed,
                "n_samples_train": n_samples_train,
                "framework": "standard",
                "n_eval": n_eval,
                "use_standard_scaler": args.use_standard_scaler,
                "reference_seed": ref_meta["reference_seed"],
                "standard_resampling_steps": args.standard_resampling_steps,
                **standard_metrics,
            }
            results.append(add_intervention_columns(standard_row, y2_values, y5_values))
            print(
                "Standard metrics: "
                f"energy={standard_metrics['energy_distance']:.6f}, "
                f"mmd2={standard_metrics['mmd2']:.6f}, "
                f"sigma2={standard_metrics['mmd_sigma2']:.6f}"
            )

            del ddpm_standard
            if device.startswith("cuda"):
                torch.cuda.empty_cache()

            results_df = pd.DataFrame(results)
            results_df.to_csv(results_file, index=False)
            print(f"\nSaved incremental results to: {results_file}")

    results_df = pd.DataFrame(results)
    results_df.to_csv(results_file, index=False)

    summary = results_df.groupby(["n_samples_train", "framework"]).agg(
        {
            "energy_distance": ["mean", "std", "count"],
            "mmd2": ["mean", "std", "count"],
        }
    )
    summary.to_csv(summary_file)

    print("\nFinal summary")
    with pd.option_context("display.max_columns", None, "display.width", 140):
        print(summary.round(6))
    print(f"\nDetailed results: {results_file}")
    print(f"Summary: {summary_file}")


if __name__ == "__main__":
    main()
