"""
random_dag_distribution_comparison.py

Distributional comparison for randomly sampled 6-slate DAGs under do(Y2, Y5).

For each seed, the DAG and functional forms match random_dag_comparison.py:
  - DAG seed = seed
  - function_seed = seed

Conditional framework:
  Samples the causal post-intervention distribution of (Y1, Y3, Y4, Y6).

Standard framework:
  Samples the observational conditional distribution
  (Y1, Y3, Y4, Y6) | Y2, Y5.

Reference data, training data, and graph structures are generated by
random_dag_data_comparison.py.
"""

import argparse
import os
import random

import numpy as np
import pandas as pd
import torch
import torch.optim as optim
from sklearn.preprocessing import QuantileTransformer, StandardScaler

from _project_setup import PROJECT_ROOT
from long_chain_distribution_comparison import (
    add_intervention_columns,
    compute_metrics,
    generate_conditional_do_samples,
    generate_standard_conditional_samples,
)
from random_dag_data_comparison import (
    N_FEATURES,
    TARGET_INDICES,
    reference_data_path,
    training_data_path,
)
from utils.conditional_ddpm import train_all_conditional_ddpms
from utils.ddpm import MyDDPM, training_loop
from utils.utils_model import MLPDiffusionContinuous


def seed_everything(seed):
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def random_dag_groups():
    groups = torch.zeros(N_FEATURES, dtype=torch.long)
    for slate_idx in range(6):
        groups[slate_idx * 5 : (slate_idx + 1) * 5] = slate_idx
    return groups


def load_reference(reference_data_dir, edge_prob, seed, n_samples_eval=None):
    path = reference_data_path(reference_data_dir, edge_prob, seed)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing reference file: {path}\n"
            "Generate reference data first with:\n"
            "  python random_dag_data_comparison.py"
        )

    data = np.load(path, allow_pickle=True)
    required = {"target_samples", "target_indices", "y2_values", "y5_values", "dag_adjacency"}
    missing = required.difference(data.files)
    if missing:
        raise ValueError(f"Reference file is missing fields: {sorted(missing)}")

    target_samples = np.asarray(data["target_samples"], dtype=float)
    target_indices = np.asarray(data["target_indices"], dtype=int)
    y2_values = np.asarray(data["y2_values"], dtype=float)
    y5_values = np.asarray(data["y5_values"], dtype=float)
    dag_adjacency = np.asarray(data["dag_adjacency"], dtype=np.float32)

    if not np.array_equal(target_indices, TARGET_INDICES):
        raise ValueError(
            "Reference target indices do not match expected (Y1, Y3, Y4, Y6) indices."
        )
    if y2_values.shape != (5,) or y5_values.shape != (5,):
        raise ValueError("Reference y2_values and y5_values must both be 5-vectors.")

    if n_samples_eval is not None:
        if n_samples_eval > target_samples.shape[0]:
            raise ValueError(
                f"Requested n_samples_eval={n_samples_eval}, but reference only has "
                f"{target_samples.shape[0]} rows."
            )
        target_samples = target_samples[:n_samples_eval]

    metadata = {
        "reference_path": path,
        "reference_seed": int(np.asarray(data["reference_seed"]).item())
        if "reference_seed" in data.files
        else None,
        "sample_seed": int(np.asarray(data["sample_seed"]).item())
        if "sample_seed" in data.files
        else None,
        "sigma": float(np.asarray(data["sigma"]).item()) if "sigma" in data.files else None,
        "correlation": float(np.asarray(data["correlation"]).item())
        if "correlation" in data.files
        else None,
        "n_edges": int(np.asarray(data["n_edges"]).item()) if "n_edges" in data.files else None,
    }
    return target_samples, y2_values, y5_values, dag_adjacency, metadata


def load_training_data(
    training_data_dir,
    edge_prob,
    n_samples_train,
    seed,
    expected_dag=None,
    sigma=None,
    correlation=None,
):
    path = training_data_path(training_data_dir, edge_prob, n_samples_train, seed)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing training data file: {path}\n"
            "Generate training data first with:\n"
            "  python random_dag_data_comparison.py\n"
            "or pass --training_data_dir to the directory containing train_*.npz files."
        )

    data = np.load(path, allow_pickle=True)
    if "train_data" not in data.files:
        raise ValueError(f"Training data file does not contain 'train_data': {path}")

    train_data = np.asarray(data["train_data"], dtype=float)
    if train_data.shape != (n_samples_train, N_FEATURES):
        raise ValueError(
            f"Unexpected train_data shape in {path}: {train_data.shape}; "
            f"expected ({n_samples_train}, {N_FEATURES})."
        )

    file_seed = int(np.asarray(data["seed"]).item()) if "seed" in data.files else None
    file_n = (
        int(np.asarray(data["n_samples_train"]).item())
        if "n_samples_train" in data.files
        else None
    )
    if file_seed is not None and file_seed != seed:
        raise ValueError(f"Seed mismatch in {path}: file has {file_seed}, expected {seed}.")
    if file_n is not None and file_n != n_samples_train:
        raise ValueError(
            f"Training-size mismatch in {path}: file has {file_n}, expected {n_samples_train}."
        )

    if expected_dag is not None and "dag_adjacency" in data.files:
        file_dag = np.asarray(data["dag_adjacency"], dtype=np.float32)
        if not np.array_equal(file_dag, expected_dag):
            raise ValueError(f"DAG mismatch between reference and training data: {path}")

    if sigma is not None and "sigma" in data.files:
        file_sigma = float(np.asarray(data["sigma"]).item())
        if not np.isclose(file_sigma, sigma):
            print(f"Warning: {path} has sigma={file_sigma}, requested sigma={sigma}.")
    if correlation is not None and "correlation" in data.files:
        file_correlation = float(np.asarray(data["correlation"]).item())
        if not np.isclose(file_correlation, correlation):
            print(
                f"Warning: {path} has correlation={file_correlation}, "
                f"requested correlation={correlation}."
            )

    return train_data, path


def fit_scaler(train_data, use_standard_scaler, seed):
    if use_standard_scaler:
        scaler = StandardScaler()
    else:
        scaler = QuantileTransformer(
            output_distribution="normal",
            random_state=seed,
            n_quantiles=min(1000, train_data.shape[0]),
            subsample=min(100000, train_data.shape[0]),
        )
    train_data_norm = scaler.fit_transform(train_data)
    return scaler, train_data_norm


def main():
    parser = argparse.ArgumentParser(
        description="Random-DAG distribution comparison under do(Y2, Y5)."
    )
    parser.add_argument("--device", type=str, default="cuda:0")
    parser.add_argument("--n_seeds", type=int, default=50)
    parser.add_argument("--edge_prob", type=float, default=0.5)
    parser.add_argument(
        "--training_samples",
        type=int,
        nargs="+",
        default=[500, 1000, 2000, 5000],
    )
    parser.add_argument(
        "--reference_data_dir",
        type=str,
        default="./data/random_dag_distribution_comparison/references",
    )
    parser.add_argument(
        "--training_data_dir",
        type=str,
        default="./data/random_dag_distribution_comparison/training",
    )
    parser.add_argument("--n_samples_eval", type=int, default=None)
    parser.add_argument("--sample_batch_size", type=int, default=5000)
    parser.add_argument("--standard_resampling_steps", type=int, default=20)
    parser.add_argument("--metric_chunk_size", type=int, default=256)
    parser.add_argument("--median_subset_size", type=int, default=1000)
    parser.add_argument("--use_standard_scaler", action="store_true")
    parser.add_argument("--n_steps", type=int, default=1000)
    parser.add_argument("--n_epochs", type=int, default=3000)
    parser.add_argument("--lr", type=float, default=5e-5)
    parser.add_argument("--sigma", type=float, default=1.0)
    parser.add_argument("--correlation", type=float, default=0.5)
    parser.add_argument(
        "--results_dir",
        type=str,
        default="./results/random_dag_distribution_comparison",
    )
    parser.add_argument("--verbose_training", action="store_true")
    args = parser.parse_args()

    device = args.device
    if device.startswith("cuda") and not torch.cuda.is_available():
        print(f"CUDA is not available. Using CPU instead of {device}.")
        device = "cpu"

    os.makedirs(args.results_dir, exist_ok=True)

    groups_conditional = random_dag_groups()
    groups_standard = torch.zeros(N_FEATURES, dtype=torch.long)
    adjacency_standard = torch.ones((1, 1), dtype=torch.float32)

    d_time_standard = 128
    hidden_dims_standard = [1024, 512, 512, 512, 256]
    hidden_dims_conditional = [512, 256, 256, 256, 128]
    dim_t_conditional = 128

    scaler_suffix = "_std" if args.use_standard_scaler else "_qt"
    results_file = os.path.join(
        args.results_dir,
        f"random_dag_distribution_comparison_results_{scaler_suffix.lstrip('_')}.csv",
    )
    summary_file = os.path.join(
        args.results_dir,
        f"random_dag_distribution_comparison_summary_{scaler_suffix.lstrip('_')}.csv",
    )

    print("\nRandom-DAG distribution comparison")
    print(f"edge_prob: {args.edge_prob}")
    print(f"Reference data dir: {args.reference_data_dir}")
    print(f"Training data dir: {args.training_data_dir}")
    print(f"Training sizes: {args.training_samples}")
    print(f"Seeds: 0 to {args.n_seeds - 1}")
    print(f"Sample batch size: {args.sample_batch_size}")
    print(f"Metric chunk size: {args.metric_chunk_size}")

    if os.path.exists(results_file):
        os.remove(results_file)

    results = []

    for seed in range(args.n_seeds):
        print(f"\n{'=' * 80}")
        print(f"SEED {seed}")
        print(f"{'=' * 80}")

        reference, y2_values, y5_values, dag_adjacency, ref_meta = load_reference(
            reference_data_dir=args.reference_data_dir,
            edge_prob=args.edge_prob,
            seed=seed,
            n_samples_eval=args.n_samples_eval,
        )
        n_eval = reference.shape[0]
        n_edges = int(np.sum(dag_adjacency))
        adjacency_conditional = torch.tensor(dag_adjacency, dtype=torch.float32)

        print(f"Reference target shape: {reference.shape}")
        print(f"Y2 intervention: {y2_values}")
        print(f"Y5 intervention: {y5_values}")
        print(f"DAG edges: {n_edges}")

        for n_samples_train in args.training_samples:
            print(f"\n{'-' * 80}")
            print(f"Seed {seed} | training samples: {n_samples_train}")
            print(f"{'-' * 80}")

            train_data, train_data_path_used = load_training_data(
                training_data_dir=args.training_data_dir,
                edge_prob=args.edge_prob,
                n_samples_train=n_samples_train,
                seed=seed,
                expected_dag=dag_adjacency,
                sigma=args.sigma,
                correlation=args.correlation,
            )
            print(f"Loaded training data: {train_data_path_used}")

            scaler, train_data_norm = fit_scaler(train_data, args.use_standard_scaler, seed)
            train_tensor = torch.tensor(train_data_norm, dtype=torch.float32)

            print("\nTraining conditional framework")
            seed_everything(seed)
            conditional_models = train_all_conditional_ddpms(
                train_data=train_tensor,
                groups=groups_conditional,
                A=adjacency_conditional.cpu().numpy(),
                hidden_dims=hidden_dims_conditional,
                dim_t=dim_t_conditional,
                n_steps=args.n_steps,
                n_epochs=args.n_epochs,
                lr=args.lr,
                device=device,
                verbose=args.verbose_training,
            )

            print("\nSampling conditional do-distribution")
            conditional_samples = generate_conditional_do_samples(
                models=conditional_models,
                groups=groups_conditional,
                adjacency=adjacency_conditional,
                scaler=scaler,
                y2_values=y2_values,
                y5_values=y5_values,
                n_samples=n_eval,
                batch_size=args.sample_batch_size,
                device=device,
            )

            conditional_metrics = compute_metrics(
                reference,
                conditional_samples,
                chunk_size=args.metric_chunk_size,
                median_subset_size=args.median_subset_size,
                seed=100000 + seed,
            )
            conditional_row = {
                "seed": seed,
                "n_samples_train": n_samples_train,
                "edge_prob": args.edge_prob,
                "n_edges": n_edges,
                "framework": "conditional",
                "n_eval": n_eval,
                "use_standard_scaler": args.use_standard_scaler,
                "reference_seed": ref_meta["reference_seed"],
                "sample_seed": ref_meta["sample_seed"],
                "standard_resampling_steps": np.nan,
                **conditional_metrics,
            }
            results.append(add_intervention_columns(conditional_row, y2_values, y5_values))
            print(
                "Conditional metrics: "
                f"energy={conditional_metrics['energy_distance']:.6f}, "
                f"mmd2={conditional_metrics['mmd2']:.6f}, "
                f"sigma2={conditional_metrics['mmd_sigma2']:.6f}"
            )

            del conditional_models
            if device.startswith("cuda"):
                torch.cuda.empty_cache()

            print("\nTraining standard framework")
            seed_everything(seed)
            model_standard = MLPDiffusionContinuous(
                d_in=N_FEATURES,
                hidden_dims=hidden_dims_standard,
                dim_t=d_time_standard,
                groups_0=groups_standard,
                A=adjacency_standard,
            )
            ddpm_standard = MyDDPM(model_standard, n_steps=args.n_steps, device=device)
            optimizer_standard = optim.Adam(ddpm_standard.network.parameters(), lr=args.lr)
            training_loop(
                train_tensor,
                ddpm_standard,
                args.n_epochs,
                optimizer_standard,
                device=device,
                store_path=None,
            )

            print("\nSampling standard conditional distribution")
            standard_samples = generate_standard_conditional_samples(
                ddpm=ddpm_standard,
                scaler=scaler,
                y2_values=y2_values,
                y5_values=y5_values,
                n_samples=n_eval,
                batch_size=args.sample_batch_size,
                resampling_steps=args.standard_resampling_steps,
            )

            standard_metrics = compute_metrics(
                reference,
                standard_samples,
                chunk_size=args.metric_chunk_size,
                median_subset_size=args.median_subset_size,
                seed=200000 + seed,
            )
            standard_row = {
                "seed": seed,
                "n_samples_train": n_samples_train,
                "edge_prob": args.edge_prob,
                "n_edges": n_edges,
                "framework": "standard",
                "n_eval": n_eval,
                "use_standard_scaler": args.use_standard_scaler,
                "reference_seed": ref_meta["reference_seed"],
                "sample_seed": ref_meta["sample_seed"],
                "standard_resampling_steps": args.standard_resampling_steps,
                **standard_metrics,
            }
            results.append(add_intervention_columns(standard_row, y2_values, y5_values))
            print(
                "Standard metrics: "
                f"energy={standard_metrics['energy_distance']:.6f}, "
                f"mmd2={standard_metrics['mmd2']:.6f}, "
                f"sigma2={standard_metrics['mmd_sigma2']:.6f}"
            )

            del ddpm_standard
            if device.startswith("cuda"):
                torch.cuda.empty_cache()

            results_df = pd.DataFrame(results)
            results_df.to_csv(results_file, index=False)
            print(f"\nSaved incremental results to: {results_file}")

    results_df = pd.DataFrame(results)
    results_df.to_csv(results_file, index=False)

    summary = results_df.groupby(["n_samples_train", "framework"]).agg(
        {
            "energy_distance": ["mean", "std", "count"],
            "mmd2": ["mean", "std", "count"],
        }
    )
    summary.to_csv(summary_file)

    print("\nFinal summary")
    with pd.option_context("display.max_columns", None, "display.width", 140):
        print(summary.round(6))
    print(f"\nDetailed results: {results_file}")
    print(f"Summary: {summary_file}")


if __name__ == "__main__":
    main()
