"""
sachs_distribution_comparison.py

Distributional comparison for the Sachs DAG under interventions on:
PIP3, P38, Raf, and Erk.

Conditional framework:
  Samples the causal post-intervention distribution of the non-intervened
  variables PKC, Plcg, PKA, Jnk, PIP2, Mek, and Akt.

Standard framework:
  Samples the observational conditional distribution of those non-intervened
  variables given PIP3, P38, Raf, and Erk.

Training data is loaded from files generated by sachs_data_comparison.py so
competitors can use exactly the same dataset for each seed and training size.
"""

import argparse
import os
import random

import numpy as np
import pandas as pd
import torch
import torch.optim as optim
from sklearn.preprocessing import QuantileTransformer, StandardScaler

from _project_setup import PROJECT_ROOT
from long_chain_distribution_comparison import compute_metrics
from sachs_data_comparison import (
    INTERVENTION_INDICES,
    INTERVENTION_NAMES,
    NODE_NAMES,
    TARGET_INDICES,
    training_data_path,
)
from utils.conditional_ddpm import generate_conditional_samples, train_all_conditional_ddpms
from utils.ddpm import MyDDPM, generate_imputation, training_loop
from utils.utils_model import MLPDiffusionContinuous


N_FEATURES = 11


def seed_everything(seed):
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def sachs_groups_and_adjacency():
    groups = torch.arange(N_FEATURES, dtype=torch.long)
    adjacency = torch.zeros(N_FEATURES, N_FEATURES, dtype=torch.float32)

    adjacency[0, 2] = 1
    adjacency[0, 4] = 1
    adjacency[0, 5] = 1
    adjacency[0, 6] = 1
    adjacency[0, 8] = 1
    adjacency[1, 3] = 1
    adjacency[1, 7] = 1
    adjacency[2, 4] = 1
    adjacency[2, 5] = 1
    adjacency[2, 6] = 1
    adjacency[2, 8] = 1
    adjacency[2, 9] = 1
    adjacency[2, 10] = 1
    adjacency[3, 7] = 1
    adjacency[4, 8] = 1
    adjacency[8, 9] = 1
    adjacency[9, 10] = 1

    return groups, adjacency


def load_reference(reference_path, n_samples_eval=None):
    if not os.path.exists(reference_path):
        raise FileNotFoundError(
            f"Missing reference file: {reference_path}\n"
            "Create it first with sachs_data_comparison.py."
        )

    data = np.load(reference_path, allow_pickle=True)
    required = {
        "target_samples",
        "target_indices",
        "intervention_indices",
        "intervention_values",
    }
    missing = required.difference(data.files)
    if missing:
        raise ValueError(f"Reference file is missing fields: {sorted(missing)}")

    target_samples = np.asarray(data["target_samples"], dtype=float)
    target_indices = np.asarray(data["target_indices"], dtype=int)
    intervention_indices = np.asarray(data["intervention_indices"], dtype=int)
    intervention_values = np.asarray(data["intervention_values"], dtype=float)

    if not np.array_equal(target_indices, TARGET_INDICES):
        raise ValueError("Reference target indices do not match the Sachs target indices.")
    if not np.array_equal(intervention_indices, INTERVENTION_INDICES):
        raise ValueError("Reference intervention indices do not match PIP3, P38, Raf, Erk.")
    if intervention_values.shape != (len(INTERVENTION_INDICES),):
        raise ValueError("Reference intervention_values has the wrong shape.")

    if n_samples_eval is not None:
        if n_samples_eval > target_samples.shape[0]:
            raise ValueError(
                f"Requested n_samples_eval={n_samples_eval}, but reference only has "
                f"{target_samples.shape[0]} rows."
            )
        target_samples = target_samples[:n_samples_eval]

    metadata = {
        "reference_seed": int(np.asarray(data["seed"]).item()) if "seed" in data.files else None,
        "sigma": float(np.asarray(data["sigma"]).item()) if "sigma" in data.files else None,
    }
    return target_samples, intervention_indices, intervention_values, metadata


def fit_scaler(train_data, use_standard_scaler, seed):
    if use_standard_scaler:
        scaler = StandardScaler()
    else:
        scaler = QuantileTransformer(
            output_distribution="normal",
            random_state=seed,
            n_quantiles=min(1000, train_data.shape[0]),
            subsample=min(100000, train_data.shape[0]),
        )
    train_data_norm = scaler.fit_transform(train_data)
    return scaler, train_data_norm


def load_training_data(training_data_dir, n_samples_train, seed, sigma=None):
    path = training_data_path(training_data_dir, n_samples_train, seed)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing training data file: {path}\n"
            "Generate training data first with:\n"
            "  python sachs_data_comparison.py\n"
            "or pass --training_data_dir to the directory containing train_n*_seed*.npz files."
        )

    data = np.load(path, allow_pickle=True)
    if "train_data" not in data.files:
        raise ValueError(f"Training data file does not contain 'train_data': {path}")

    train_data = np.asarray(data["train_data"], dtype=float)
    if train_data.shape != (n_samples_train, N_FEATURES):
        raise ValueError(
            f"Unexpected train_data shape in {path}: {train_data.shape}; "
            f"expected ({n_samples_train}, {N_FEATURES})."
        )

    file_seed = int(np.asarray(data["seed"]).item()) if "seed" in data.files else None
    file_n = (
        int(np.asarray(data["n_samples_train"]).item())
        if "n_samples_train" in data.files
        else None
    )
    if file_seed is not None and file_seed != seed:
        raise ValueError(f"Seed mismatch in {path}: file has {file_seed}, expected {seed}.")
    if file_n is not None and file_n != n_samples_train:
        raise ValueError(
            f"Training-size mismatch in {path}: file has {file_n}, expected {n_samples_train}."
        )

    if sigma is not None and "sigma" in data.files:
        file_sigma = float(np.asarray(data["sigma"]).item())
        if not np.isclose(file_sigma, sigma):
            print(f"Warning: {path} has sigma={file_sigma}, requested sigma={sigma}.")

    return train_data, path


def intervention_row(intervention_indices, intervention_values):
    row = np.zeros((1, N_FEATURES))
    row[:, intervention_indices] = intervention_values
    return row


def normalized_intervention_row(scaler, intervention_indices, intervention_values):
    return scaler.transform(intervention_row(intervention_indices, intervention_values))[0]


def inverse_target_samples(scaler, target_norm, intervention_norm, intervention_indices):
    full_norm = np.zeros((target_norm.shape[0], N_FEATURES))
    full_norm[:, TARGET_INDICES] = target_norm
    full_norm[:, intervention_indices] = intervention_norm[intervention_indices]
    full_orig = scaler.inverse_transform(full_norm)
    return full_orig[:, TARGET_INDICES]


def generate_conditional_do_samples_sachs(
    models,
    groups,
    adjacency,
    scaler,
    intervention_indices,
    intervention_values,
    n_samples,
    batch_size,
    device,
):
    intervention_norm = normalized_intervention_row(
        scaler, intervention_indices, intervention_values
    )
    do_vars = {}
    for idx in intervention_indices:
        do_vars[int(idx)] = torch.tensor(
            [intervention_norm[idx]], dtype=torch.float32, device=device
        )

    batches = []
    for start in range(0, n_samples, batch_size):
        current_batch = min(batch_size, n_samples - start)
        print(f"    Conditional sampling batch {start // batch_size + 1}: {current_batch}")
        samples_norm = generate_conditional_samples(
            models=models,
            groups=groups,
            A=adjacency.cpu().numpy(),
            do_vars=do_vars,
            sample_vars=TARGET_INDICES.tolist(),
            n_samples=current_batch,
            device=device,
            verbose=False,
        )
        target_norm = samples_norm[:, 0, :].detach().cpu().numpy()
        batches.append(
            inverse_target_samples(scaler, target_norm, intervention_norm, intervention_indices)
        )

    return np.concatenate(batches, axis=0)


def generate_standard_conditional_samples_sachs(
    ddpm,
    scaler,
    intervention_indices,
    intervention_values,
    n_samples,
    batch_size,
    resampling_steps,
):
    batches = []
    base_row = intervention_row(intervention_indices, intervention_values)

    for start in range(0, n_samples, batch_size):
        current_batch = min(batch_size, n_samples - start)
        print(f"    Standard sampling batch {start // batch_size + 1}: {current_batch}")

        batch_orig = np.repeat(base_row, repeats=current_batch, axis=0)
        batch_norm = scaler.transform(batch_orig)
        input_norm = torch.tensor(batch_norm, dtype=torch.float32)

        input_mask = torch.zeros(input_norm.shape, dtype=torch.float32)
        input_mask[:, intervention_indices.tolist()] = 1.0

        output_norm = generate_imputation(
            ddpm,
            input_norm,
            input_mask,
            resampling_steps=resampling_steps,
        )
        output_orig = scaler.inverse_transform(output_norm.detach().cpu().numpy())
        batches.append(output_orig[:, TARGET_INDICES])

    return np.concatenate(batches, axis=0)


def add_intervention_columns(row, intervention_values):
    for name, value in zip(INTERVENTION_NAMES, intervention_values):
        row[f"{name.lower()}_value"] = float(value)
    return row


def main():
    parser = argparse.ArgumentParser(
        description="Sachs distribution comparison under do(PIP3, P38, Raf, Erk)."
    )
    parser.add_argument("--device", type=str, default="cuda:0")
    parser.add_argument("--n_seeds", type=int, default=50)
    parser.add_argument(
        "--training_samples",
        type=int,
        nargs="+",
        default=[500, 1000, 2000, 5000],
    )
    parser.add_argument(
        "--reference_path",
        type=str,
        default="./data/sachs_distribution_comparison/true_do_reference.npz",
    )
    parser.add_argument(
        "--training_data_dir",
        type=str,
        default="./data/sachs_distribution_comparison/training",
    )
    parser.add_argument("--n_samples_eval", type=int, default=None)
    parser.add_argument("--sample_batch_size", type=int, default=5000)
    parser.add_argument("--standard_resampling_steps", type=int, default=20)
    parser.add_argument("--metric_chunk_size", type=int, default=256)
    parser.add_argument("--median_subset_size", type=int, default=1000)
    parser.add_argument("--use_standard_scaler", action="store_true")
    parser.add_argument("--n_steps", type=int, default=1000)
    parser.add_argument("--n_epochs", type=int, default=3000)
    parser.add_argument("--lr_standard", type=float, default=5e-5)
    parser.add_argument("--lr_conditional", type=float, default=5e-5)
    parser.add_argument("--sigma", type=float, default=1.0)
    parser.add_argument(
        "--results_dir",
        type=str,
        default="./results/sachs_distribution_comparison",
    )
    parser.add_argument("--verbose_training", action="store_true")
    args = parser.parse_args()

    device = args.device
    if device.startswith("cuda") and not torch.cuda.is_available():
        print(f"CUDA is not available. Using CPU instead of {device}.")
        device = "cpu"

    os.makedirs(args.results_dir, exist_ok=True)

    reference, intervention_indices, intervention_values, ref_meta = load_reference(
        args.reference_path, n_samples_eval=args.n_samples_eval
    )
    n_eval = reference.shape[0]

    groups_conditional, adjacency_conditional = sachs_groups_and_adjacency()
    groups_standard = torch.zeros(N_FEATURES, dtype=torch.long)
    adjacency_standard = torch.ones((1, 1), dtype=torch.float32)

    d_time_standard = 128
    hidden_dims_standard = [1024, 512, 512, 512, 256]
    hidden_dims_conditional = [512, 256, 256, 256, 128]
    dim_t_conditional = 128

    scaler_suffix = "_std" if args.use_standard_scaler else "_qt"
    results_file = os.path.join(
        args.results_dir, f"sachs_distribution_comparison_results{scaler_suffix}.csv"
    )
    summary_file = os.path.join(
        args.results_dir, f"sachs_distribution_comparison_summary{scaler_suffix}.csv"
    )

    print("\nSachs distribution comparison")
    print(f"Reference path: {args.reference_path}")
    print(f"Reference target shape: {reference.shape}")
    print("Target variables: " + ", ".join(NODE_NAMES[i] for i in TARGET_INDICES))
    print(
        "Interventions: "
        + ", ".join(
            f"{name}={value}" for name, value in zip(INTERVENTION_NAMES, intervention_values)
        )
    )
    print(f"Training data dir: {args.training_data_dir}")
    print(f"Training sizes: {args.training_samples}")
    print(f"Seeds: 0 to {args.n_seeds - 1}")
    print(f"Sample batch size: {args.sample_batch_size}")
    print(f"Metric chunk size: {args.metric_chunk_size}")

    if os.path.exists(results_file):
        os.remove(results_file)

    results = []

    for seed in range(args.n_seeds):
        print(f"\n{'=' * 80}")
        print(f"SEED {seed}")
        print(f"{'=' * 80}")
        seed_everything(seed)

        for n_samples_train in args.training_samples:
            print(f"\n{'-' * 80}")
            print(f"Seed {seed} | training samples: {n_samples_train}")
            print(f"{'-' * 80}")

            train_data, train_data_path_used = load_training_data(
                training_data_dir=args.training_data_dir,
                n_samples_train=n_samples_train,
                seed=seed,
                sigma=args.sigma,
            )
            print(f"Loaded training data: {train_data_path_used}")
            scaler, train_data_norm = fit_scaler(train_data, args.use_standard_scaler, seed)
            train_tensor = torch.tensor(train_data_norm, dtype=torch.float32)

            print("\nTraining conditional framework")
            seed_everything(seed)
            conditional_models = train_all_conditional_ddpms(
                train_data=train_tensor,
                groups=groups_conditional,
                A=adjacency_conditional.cpu().numpy(),
                hidden_dims=hidden_dims_conditional,
                dim_t=dim_t_conditional,
                n_steps=args.n_steps,
                n_epochs=args.n_epochs,
                lr=args.lr_conditional,
                device=device,
                verbose=args.verbose_training,
            )

            print("\nSampling conditional do-distribution")
            conditional_samples = generate_conditional_do_samples_sachs(
                models=conditional_models,
                groups=groups_conditional,
                adjacency=adjacency_conditional,
                scaler=scaler,
                intervention_indices=intervention_indices,
                intervention_values=intervention_values,
                n_samples=n_eval,
                batch_size=args.sample_batch_size,
                device=device,
            )

            conditional_metrics = compute_metrics(
                reference,
                conditional_samples,
                chunk_size=args.metric_chunk_size,
                median_subset_size=args.median_subset_size,
                seed=100000 + seed,
            )
            conditional_row = {
                "seed": seed,
                "n_samples_train": n_samples_train,
                "framework": "conditional",
                "n_eval": n_eval,
                "use_standard_scaler": args.use_standard_scaler,
                "reference_seed": ref_meta["reference_seed"],
                "standard_resampling_steps": np.nan,
                **conditional_metrics,
            }
            results.append(add_intervention_columns(conditional_row, intervention_values))
            print(
                "Conditional metrics: "
                f"energy={conditional_metrics['energy_distance']:.6f}, "
                f"mmd2={conditional_metrics['mmd2']:.6f}, "
                f"sigma2={conditional_metrics['mmd_sigma2']:.6f}"
            )

            del conditional_models
            if device.startswith("cuda"):
                torch.cuda.empty_cache()

            print("\nTraining standard framework")
            seed_everything(seed)
            model_standard = MLPDiffusionContinuous(
                d_in=N_FEATURES,
                hidden_dims=hidden_dims_standard,
                dim_t=d_time_standard,
                groups_0=groups_standard,
                A=adjacency_standard,
            )
            ddpm_standard = MyDDPM(model_standard, n_steps=args.n_steps, device=device)
            optimizer_standard = optim.Adam(ddpm_standard.network.parameters(), lr=args.lr_standard)
            training_loop(
                train_tensor,
                ddpm_standard,
                args.n_epochs,
                optimizer_standard,
                device=device,
                store_path=None,
            )

            print("\nSampling standard conditional distribution")
            standard_samples = generate_standard_conditional_samples_sachs(
                ddpm=ddpm_standard,
                scaler=scaler,
                intervention_indices=intervention_indices,
                intervention_values=intervention_values,
                n_samples=n_eval,
                batch_size=args.sample_batch_size,
                resampling_steps=args.standard_resampling_steps,
            )

            standard_metrics = compute_metrics(
                reference,
                standard_samples,
                chunk_size=args.metric_chunk_size,
                median_subset_size=args.median_subset_size,
                seed=200000 + seed,
            )
            standard_row = {
                "seed": seed,
                "n_samples_train": n_samples_train,
                "framework": "standard",
                "n_eval": n_eval,
                "use_standard_scaler": args.use_standard_scaler,
                "reference_seed": ref_meta["reference_seed"],
                "standard_resampling_steps": args.standard_resampling_steps,
                **standard_metrics,
            }
            results.append(add_intervention_columns(standard_row, intervention_values))
            print(
                "Standard metrics: "
                f"energy={standard_metrics['energy_distance']:.6f}, "
                f"mmd2={standard_metrics['mmd2']:.6f}, "
                f"sigma2={standard_metrics['mmd_sigma2']:.6f}"
            )

            del ddpm_standard
            if device.startswith("cuda"):
                torch.cuda.empty_cache()

            results_df = pd.DataFrame(results)
            results_df.to_csv(results_file, index=False)
            print(f"\nSaved incremental results to: {results_file}")

    results_df = pd.DataFrame(results)
    results_df.to_csv(results_file, index=False)

    summary = results_df.groupby(["n_samples_train", "framework"]).agg(
        {
            "energy_distance": ["mean", "std", "count"],
            "mmd2": ["mean", "std", "count"],
        }
    )
    summary.to_csv(summary_file)

    print("\nFinal summary")
    with pd.option_context("display.max_columns", None, "display.width", 140):
        print(summary.round(6))
    print(f"\nDetailed results: {results_file}")
    print(f"Summary: {summary_file}")


if __name__ == "__main__":
    main()
